# Этапы в порядке их вызова из workflow.
stages:

  fetch:
    name: Этап импорта статей
    # Возможен импорт из нескольких источников. Реализован PubMed.
    modules:
      - module: fetcher
        type: pubmed
        # Строка поиска по PubMed.
        term: '(((calcification[Abstract]) AND cancer) AND breast) AND ("2015/01/01"[PubDate] : "2025/12/31"[PubDate])'

  ner:
    name: Этап извлечения именованных сущностей
    # Возможна работа нескольких модулей.
    modules:
      - module: ner
        # Варианты: nltk, transformer
        type: nltk

  filter:
    name: Этап фильтрации по словарю
    # Возможна работа нескольких словарей.
    modules:
      - module: filter
        # Варианты: mesh, umls, snomed.
        type: mesh


  output:
    name: Этап вывода результатов
    modules:
      - module: output
        type: excel
        file: results.xlsx
      - module: output
        type: charts
