# Информация об эксперименте.
experiment:
  name: Тестовый запуск
  description: Тестовый запуск для проверки возможностей системы
  directory: "workflows/Тестовый запуск"
  author: Вагун И.В.

# Этапы рабочего процесса в порядке их запуска из workflow.py.
stages:


  # Можно пропустить, если статьи уже были загружены ранее с теми же параметрами.
  - name: Этап импорта статей
    modules:
      # Очистка базы статей из прошлого запуска.
      - module: cleaner
        type: database
        params:
          # Список моделей для очистки.
          models:
            - Article
      # Импорт статей.
      # Возможен запуск одного модуля несколько раз с разными параметрами.
      # Реализован PubMed Central.
      - module: fetcher
        type: pubmed-central
        params:
          # Строка поиска по PubMed Central.
          # Документация: https://pmc.ncbi.nlm.nih.gov/about/userguide/
          term: '(((calcification[Abstract]) AND cancer) AND breast) AND ("2015/01/01"[PubDate] : "2025/12/31"[PubDate])'
          # Лимит поиска
          retmax: 10000

  - name: Этап извлечения именованных сущностей
    # Возможна работа нескольких модулей.
    # Есть привязка термина к модулю, который его извлек.
    # Если термин извлечен несколькими модулями, сохраняется привязка к ним всем.
    modules:
      # Очистка базы данных от прошлого запуска
      - module: cleaner
        type: database
        params:
          models:
            - Term
      - module: ner
        # Варианты: pos-based-hybrid, transformer
        type: pos-based-hybrid
        params:
          stopwords:
            - resources/dictionaries/stop-words/AidaStopWords.xlsx

  - name: Этап поиска в словаре
    # Возможна работа нескольких словарей
    modules:
      - module: dictionary
        # Варианты: MeSH, SNOMED CT.
        type: MeSH
      - module: dictionary
        # Варианты: MeSH, SNOMED CT.
        type: SNOMED CT

  - name: Этап вывода результатов
    modules:
      # Запись в Excel всех извлеченных терминов по годам с указанием вхождения в словари
      - module: output
        type: excel
        params:
          # Варианты: MeSH, SNOMED CT.
          dictionaries:
            - MeSH
            - SNOMED CT
#      # Построение диаграмм по извлеченным терминам
#      - module: output
#        type: charts
#        params:
#          # Варианты: MeSH, SNOMED CT.
#          dictionaries:
#            - MeSH
