# Информация об эксперименте
experiment:
  description: Тестовый запуск

# Этапы в порядке их вызова из workflow.
stages:


  - name: Этап импорта статей
    # Возможен импорт из нескольких источников, а также запуск одного модуля несколько раз с разными параметрами.
    # Реализован PubMed Central.
    modules:
      - module: fetcher
        type: pubmed-central
        params:
          # Строка поиска по PubMed.
          #          term: '(((calcification[Abstract]) AND cancer) AND breast) AND ("2015/01/01"[PubDate] : "2025/12/31"[PubDate])'
          term: '(((calcification[Abstract]) AND cancer) AND breast) AND ("2003/01/01"[PubDate] : "2021/31/12"[PubDate])'
          # Лимит поиска
          retmax: 10000

  - name: Этап извлечения именованных сущностей
    # Возможна работа нескольких модулей.
    modules:
      - module: ner
        # Варианты: pos-based-hybrid, transformer
        type: pos-based-hybrid
        params:
          stopwords:
            - resources/dictionaries/stop-words/AidaStopWords.xlsx

#  - name: Этап фильтрации по словарю
#    # Возможна работа нескольких словарей.
#    modules:
#      - module: filter
#        # Варианты: mesh, umls, snomed.
#        type: mesh
#
#
#  - name: Этап вывода результатов
#    modules:
#      - module: output
#        type: excel
#        file: results.xlsx
#      - module: output
#        type: charts
