# Модули в порядке их вызова из workflow.
modules:

  import:
    name: Модуль импорта статей
    type: import
    # Возможен импорт из нескольких источников. Реализован PubMed.
    stages:
      - type: "PubMed"
        # Строка поиска по PubMed.
        term: '(((calcification[Abstract]) AND cancer) AND breast) AND ("2015/01/01"[PubDate] : "2025/12/31"[PubDate])'

  ner:
    name: Модуль извлечения именованных сущностей
    type: ner
    # Возможна работа нескольких модулей.
    stages:
      # Варианты: nltk, transformer
      - type: "nltk"

  filter:
    name: Модуль фильтра по словарю
    type: filter
    # Возможна работа нескольких словарей.
    stages:
      # Варианты: mesh, umls, snomed.
      - type: "mesh"

  output:
    name: Модуль вывода результатов
    type: output
    stages:
      - type: excel
        file: results.xlsx
      - type: charts
